services:
    RedisStorageService:
      class: Redis
      factory: '@App\Infrastructure\Factory\RedisFactory'

when@test:
    services:
        RedisStorageService:
          class: Redis
          public: true
